[package]
authors = ["D1plo1d <thatotherdude@gmail.com>"]
edition = "2018"
name = "teg-machine"
version = "0.1.0"

[lib]
name = "machine"
path = "src/lib.rs"

# [profile.release]
# # opt-level = "z"
# lto = true

[dependencies]
anyhow = "1.0"
async-graphql = "2.2.0"
# async-graphql-warp = { path = "../../../async-graphql/async-graphql-warp" }
# async-graphql = { path = "../../../async-graphql" }
futures = "0.3.5"
serde_json = { version = "1.0.44", features = ["raw_value"] }
toml = "0.5.6"
async-trait = "0.1.36"
derive-new = "0.5.8"
teg-protobufs = { path= "../protobufs" }
bytes = "0.5.6"
arc-swap = "0.4.7"
tracing = "0.1.19"
tracing-futures = "0.2.4"
xactor = "0.7.8"
async-codec = "0.4.0"
sqlx = { version = "0.4.2", features = [ "runtime-async-std-native-tls", "sqlite", "offline" ] }
rand = "0.7.3"
smart-default = "0.6.0"
schemars = "0.8.0"
jsonschema = "0.4.3"
nanoid = "0.3.0"

[dependencies.async-std]
features = ["tokio02", "unstable"]
version = "1.6.3"

[dependencies.chrono]
features = ["serde"]
version = "0.4.10"

[dependencies.serde]
features = ["derive"]
version = "1.0.104"

[patch.crates-io]
