name: tegh-host
version: git
summary: A graphql server for 3D printers
description: >
  A graphql server for 3D printers

confinement: devmode
base: core18

parts:
  python-dependency:
    plugin: python
    python-version: python2
    source: .
  tegh-host:
    plugin: nodejs
    source: './'
    nodejs-version: '11.6.0'
    nodejs-yarn-version: 'v1.12.3'
    # "node-webcrypto-ossl": "^1.0.38",

    # node-packages:
    #   - '@trust/webcrypto'
    #   - 'node-webcrypto-ossl'
    #   - 'wrtc'
    #   - 'ws'
    #   - 'serialport'
apps:
  tegh-host:
    command: tegh-host
