[package]
name = "teg-auth"
version = "0.1.0"
authors = ["D1plo1d <thatotherdude@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
diesel = { version = "1.4.3", features = ["postgres", "r2d2"] }
diesel_logger = "0.1.0"
dotenv = "0.15.0"
juniper = "0.14.2"
juniper_warp = "0.5.2"
warp = "0.1.20"
log = "0.4.8"
env_logger = "0.7.1"
graphql_client = "0.8.0"
serde = { version = "1.0.104", features = ["derive"] }
reqwest = { version = "0.10.1", features = ["blocking", "json"] }
sqlx = { version = "0.2.4", features = ["postgres", "chrono"] }
sqlx-core = "0.2.4"
async-std = { version = "1.4.0", features = ["attributes"] }
futures = "0.3.1"
chrono = "0.4.10"
secp256k1 = { version = "0.17.2", features = ["rand"] }
rand = "0.5.6"
qrcodegen = "1.5.0"
rmp-serde = "0.14.0"
data-encoding = "2.1.2"
toml = "0.5.6"