[package]
authors = ["D1plo1d <thatotherdude@gmail.com>"]
default-run = "teg-auth"
edition = "2018"
name = "teg-auth"
version = "0.1.0"
[[bin]]
name = "teg-auth"
path = "src/bin/main.rs"

[[bin]]
name = "teg-add-invite"
path = "src/bin/add_invite.rs"

[dependencies]
anyhow = "1.0"
async-graphql-warp = "1.16.6"
data-encoding = "2.1.2"
dotenv = "0.15.0"
env_logger = "0.7.1"
error-chain = "0.12.1"
frank_jwt = "3.1.2"
futures = "0.3.1"
gravatar = "0.2.0"
hex = "0.4.0"
log = "0.4.8"
log-derive = "0.4.0"
notify = "4.0.15"
qr2term = "0.1.7"
quote = "*"
rand = "0.5.6"
rmp-serde = "0.14.0"
serde_cbor = "0.11.1"
serde_json = "1.0.44"
sled = "0.32.0-rc1"
smol-potat = "0.3.3"
syn = "*"
thiserror = "1.0.20"
toml = "0.5.6"
url = "2.1.1"
warp = "0.2.2"
versioned_sled_model = { path = "../versioned_sled_model/" }
async-trait = "0.1.36"

[dependencies.async-graphql]
branch = "patch-1"
git = "https://github.com/D1plo1d/async-graphql.git"

[dependencies.async-std]
features = ["attributes"]
version = "1.4.0"

[dependencies.chrono]
features = ["serde"]
version = "0.4.10"

[dependencies.openssl]
features = ["vendored"]
version = "0.10.28"

[dependencies.reqwest]
default-features = false
features = ["blocking", "json", "rustls-tls"]
version = "0.10.1"

[dependencies.secp256k1]
features = ["rand"]
version = "0.17.2"

[dependencies.serde]
features = ["derive"]
version = "1.0.104"

[dependencies.smol]
features = ["tokio02"]
version = "0.1.18"

[dependencies.sqlx]
branch = "feature/cargo-sqlx-migrate"
features = ["postgres", "chrono"]
git = "https://github.com/JesperAxelsson/sqlx"

[lib]
name = "teg_auth"
path = "src/lib.rs"

[patch]
[patch.crates-io]
[patch.crates-io.async-graphql]
branch = "patch-1"
git = "https://github.com/D1plo1d/async-graphql.git"
