[package]
authors = ["D1plo1d <thatotherdude@gmail.com>"]
default-run = "teg-auth"
edition = "2018"
name = "teg-auth"
version = "0.1.0"
[[bin]]
name = "teg-auth"
path = "src/bin/main.rs"

[[bin]]
name = "teg-add-invite"
path = "src/bin/add_invite.rs"

[[bin]]
name = "teg-restore-backup"
path = "src/bin/restore_backup.rs"

[dependencies]
anyhow = "1.0"
async-graphql-warp = "1.17.3"
data-encoding = "2.1.2"
dotenv = "0.15.0"
env_logger = "0.7.1"
error-chain = "0.12.1"
frank_jwt = "3.1.2"
futures = "0.3.5"
gravatar = "0.2.0"
hex = "0.4.0"
log = "0.4.8"
notify = "4.0.15"
qr2term = "0.1.7"
rand = "0.5.6"
rmp-serde = "0.14.0"
serde_cbor = "0.11.1"
serde_json = { version = "1.0.44", features = ["raw_value"] }
# sled = "0.34.2"
sled = { path = "../../../sled/" }
# sled = { git = "https://github.com/D1plo1d/sled.git", branch = "feature/any_error_into_transaction" }
thiserror = "1.0.20"
toml = "0.5.6"
url = "2.1.1"
warp = "0.2.4"
versioned_sled_model = { path = "../versioned_sled_model/" }
async-trait = "0.1.36"
base64 = "0.12.3"
sha2 = "0.9.1"
itertools = "0.9.0"
lazy_static = "1.4.0"
tempfile = "3.1.0"
clap = "3.0.0-beta.1"
humantime = "2.0.1"
surf = "2.0.0-alpha.4"
nom = "5.1.2"
async-graphql = "1.17.4"
derive-new = "0.5.8"
teg-protobufs = { path= "../teg-protobufs" }
bytes = "0.5.6"
arc-swap = "0.4.7"
pin-project = "0.4.23"
nom-gcode = "0.1.0"

[dependencies.async-std]
features = ["tokio02"]
version = "1.6.3"

[dependencies.chrono]
features = ["serde"]
version = "0.4.10"

[dependencies.openssl]
features = ["vendored"]
version = "0.10.28"

[dependencies.secp256k1]
features = ["rand"]
version = "0.17.2"

[dependencies.serde]
features = ["derive"]
version = "1.0.104"

[lib]
name = "teg_auth"
path = "src/lib.rs"

[patch]
[patch.crates-io]
