[package]
name = "teg-rust-experimental"
version = "0.1.0"
authors = ["D1plo1d <thatotherdude@gmail.com>"]
edition = "2018"

[dependencies]
tokio-serial = "3.2"
bytes = "0.4.12"
futures = "0.1.28"
tokio = "0.1.22"
tokio-io = "0.1.12"
nanomsg = "0.7.2"
combine = "3.8.1"
