name: tegh-host
version: git
summary: A graphql server for 3D printers
description: >
  A graphql server for 3D printers

confinement: devmode
base: core18

parts:
  tegh-host:
    plugin: nodejs
    # nodejs-version: '11.6.0'
    node-packages:
      - @trust/webcrypto
      - node-webcrypto-ossl
      - wrtc
      - ws
      - serialport
apps:
  tegh-host:
    command: tegh-host
