name: tegh-host
version: git
summary: A graphql server for 3D printers
description: >
  A graphql server for 3D printers

confinement: devmode
base: core18

parts:
  tegh-host:
    plugin: nodejs
    nodejs-version: '11.6.0'
    source: ./

apps:
  tegh-host:
    command: tegh-host
