name: tegh
version: 0.5.0
summary: A graphql server for 3D printers
description: >
  A graphql server for 3D printers

confinement: devmode
grade: devel
base: core18

architectures:
  - build-on: amd64
    run-on: amd64
  - build-on: armhf
    run-on: armhf

parts:
  python-dependency:
    plugin: python
    python-version: python2
    source: .
  tegh-host:
    plugin: nodejs
    source: './'
    # nodejs-version: '11.6.0'
    # nodejs-yarn-version: 'v1.12.3'
    # "node-webcrypto-ossl": "^1.0.38",

    # node-packages:
    #   - '@trust/webcrypto'
    #   - 'node-webcrypto-ossl'
    #   - 'wrtc'
    #   - 'ws'
    #   - 'serialport'
apps:
  tegh-host:
    command: tegh
    daemon: simple
