name: teg
version: 0.8.0
summary: A graphql server for 3D printers
description: >
  Teg is an experimental 3D printing software designed from the ground up to streamline your 3D printing experience. Teg features a print queue that enables users to easily queue up prints without managing complicated file systems. To manage prints remotely Teg is built on top of encrypted, distributed web technologies so you can use your 3D printer from anywhere in the world just as easily as from your home. With Teg you can worry less and create more.

base: core18
# confinement: classic
confinement: devmode
# confinement: strict
grade: stable

architectures:
  - build-on: amd64
    run-on: amd64
  - build-on: armhf
    run-on: armhf

# plugs:
#   klipper-printers:
#     interface: system-files
#     read:
#     - /tmp
#     - /tmp/printer
#     write:
#     - /tmp/printer

# passthrough:
layout:
  /var/lib/teg:
    bind: $SNAP_DATA/var
  /etc/teg:
    bind: $SNAP_DATA/etc

hooks:
  install:
    plugs:
      - account-control

# see https://docs.snapcraft.io/node-apps/6747
parts:
  # teg:
  #   plugin: nodejs
  #   nodejs-version: 12.11.1
  #   override-build: |
  #     export PATH=$PATH:$(pwd)/../npm/bin
  #
  #     yarn pkg:build
  #
  #     rsync -a --include="*.node" --include="*/" --exclude="*" --prune-empty-dirs ./node_modules ./pruned
  #     rm -rf ./packages
  #
  #     cp ./teg ../install/teg
  #     cp -r ./pruned/node_modules ../install/
  #   build-packages:
  #     - rsync
  #     - python
  #   source: https://github.com/tegapp/teg.git
  #   source-type: git
  #   source-branch: feature/printer-process
  #   source-depth: 1
  #   build-attributes: [no-patchelf]

  teg:
    plugin: dump
    source: .
    override-build: |
      if [ "$SNAPCRAFT_ARCH_TRIPLET" = "arm-linux-gnueabihf" ]; then
        echo "ARM TEG"
        cp -r ./teg-armv7-bin/* ../install/
      elif [ "$SNAPCRAFT_ARCH_TRIPLET" = "x86_64-linux-gnu" ]; then
        echo "X64 TEG"
        cp -r ./teg-x64-bin/* ../install/
      else
        echo "Error! Invalid Architecture: $SNAPCRAFT_ARCH_TRIPLET" 1>&2
        exit 1
      fi
    build-attributes: [no-patchelf]

  teg-marlin:
    plugin: dump
    source: teg-marlin-bin/
    override-build: |
      if [ "$SNAPCRAFT_ARCH_TRIPLET" = "arm-linux-gnueabihf" ]; then
        echo "ARM TEG-MARLIN"
        cp ./teg-marlin-armv7 ../install/teg-marlin
      elif [ "$SNAPCRAFT_ARCH_TRIPLET" = "x86_64-linux-gnu" ]; then
        echo "X64 TEG-MARLIN"
        cp ./teg-marlin-x64 ../install/teg-marlin
      else
        echo "Error! Invalid Architecture: $SNAPCRAFT_ARCH_TRIPLET" 1>&2
        exit 1
      fi

  # teg-marlin:
  #   plugin: rust
  #   source: https://github.com/tegapp/teg.git
  #   source-type: git
  #   source-branch: feature/printer-process
  #   source-subdir: packages/teg-marlin

apps:
  teg:
    command: teg serve
    daemon: simple
    restart-condition: always
    refresh-mode: endure
    # stop-mode: sigusr2
    plugs:
      # - klipper-printers
      - network
      - network-bind
      - process-control
      - system-observe
      - hardware-observe
      - hardware-random-control
  teg-marlin:
    command: teg-marlin
    daemon: simple
    restart-condition: always
    refresh-mode: endure
    # stop-mode: sigusr2
    plugs:
      # - klipper-printers
      - network
      - network-bind
      - process-control
      - system-observe
      - hardware-observe
      - hardware-random-control
      - raw-usb
      - gpio
      - gpio-memory-control
