name: teg
version: 0.8.0
summary: A graphql server for 3D printers
description: >
  Teg is an experimental 3D printing software designed from the ground up to streamline your 3D printing experience. Teg features a print queue that enables users to easily queue up prints without managing complicated file systems. To manage prints remotely Teg is built on top of encrypted, distributed web technologies so you can use your 3D printer from anywhere in the world just as easily as from your home. With Teg you can worry less and create more.

# confinement: classic
confinement: devmode
# confinement: strict
grade: stable

architectures:
  - build-on: amd64
    run-on: amd64

# plugs:
#   klipper-printers:
#     interface: system-files
#     read:
#     - /tmp
#     - /tmp/printer
#     write:
#     - /tmp/printer

hooks:
  install:
    plugs:
      - account-control

# see https://docs.snapcraft.io/node-apps/6747
parts:
  teg:
    plugin: dump
    source: .
    build-attributes: [no-patchelf]

apps:
  teg:
    command: teg serve
    daemon: simple
    restart-condition: always
    refresh-mode: endure
    # stop-mode: sigusr2
    plugs:
      # - klipper-printers
      - network
      - network-bind
      - process-control
      - system-observe
      - hardware-observe
      - hardware-random-control
      - raw-usb
      - gpio
      - gpio-memory-control
